### ISSUE TITLE
knife-cloud dependency is outdated

### ISSUE THREAD

**Issue by mcascone** [chef/knife-vrealize#37]
### Versions:

* Version of knife-vrealize:
knife-vrealize (3.0.0)
* Version of chef:
ChefDK version: 4.5.0
Chef Infra Client version: 15.4.45
Chef InSpec version: 4.18.0
Test Kitchen version: 2.3.3
Foodcritic version: 16.1.1
Cookstyle version: 5.9.3

### Platform Details

* Version of vRA:
version 7.0.1 (build 3621464)

### Scenario:

run `knife vra server list`

### Steps to Reproduce:

just run `knife vra server list`

### Expected Result:

a list of the vRA servers in my vra instance

### Actual Result:

```
~\Documents\github> knife vra server list
C:/opscode/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead (StructuredWarnings::StandardWarning)
Traceback (most recent call last):
        14: from C:/opscode/chefdk/bin/knife:366:in `<main>'
        13: from C:/opscode/chefdk/bin/knife:366:in `load'
        12: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/bin/knife:24:in `<top (required)>'
        11: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/application/knife.rb:162:in `run'
        10: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife.rb:223:in `run'
         9: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife.rb:160:in `subcommand_class_from'
         8: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:110:in `command_class_from'
         7: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:96:in `load_command'
         6: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:86:in `load_commands'
         5: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:86:in `each'
         4: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:86:in `block in load_commands'
         3: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:86:in `load'
         2: from C:/Users/mcascone.CONSILIO/AppData/Local/chefdk/gem/ruby/2.6.0/gems/knife-vrealize-3.0.0/lib/chef/knife/vra_catalog_list.rb:23:in `<top (required)>'
         1: from C:/opscode/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/opscode/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- chef/knife/cloud/vra_service (LoadError)
        17: from C:/opscode/chefdk/bin/knife:366:in `<main>'
        16: from C:/opscode/chefdk/bin/knife:366:in `load'
        15: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/bin/knife:24:in `<top (required)>'
        14: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/application/knife.rb:162:in `run'
        13: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife.rb:223:in `run'
        12: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife.rb:160:in `subcommand_class_from'
        11: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:110:in `command_class_from'
        10: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:96:in `load_command'
         9: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:86:in `load_commands'
         8: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:86:in `each'
         7: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:86:in `block in load_commands'
         6: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:86:in `load'
         5: from C:/Users/mcascone.CONSILIO/AppData/Local/chefdk/gem/ruby/2.6.0/gems/knife-vrealize-3.0.0/lib/chef/knife/vra_catalog_list.rb:23:in `<top (required)>'
         4: from C:/opscode/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
         3: from C:/opscode/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:123:in `rescue in require'
         2: from C:/opscode/chefdk/embedded/lib/ruby/2.6.0/rubygems.rb:217:in `try_activate'
         1: from C:/opscode/chefdk/embedded/lib/ruby/2.6.0/rubygems/specification.rb:1418:in `activate'
C:/opscode/chefdk/embedded/lib/ruby/2.6.0/rubygems/specification.rb:2302:in `raise_if_conflicts': Unable to activate knife-vrealize-3.0.0, because knife-cloud-2.0.3 conflicts with knife-cloud (~> 1.2.0) (Gem::ConflictError)
        18: from C:/opscode/chefdk/bin/knife:366:in `<main>'
        17: from C:/opscode/chefdk/bin/knife:366:in `load'
        16: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/bin/knife:24:in `<top (required)>'
        15: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/application/knife.rb:162:in `run'
        14: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife.rb:223:in `run'
        13: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife.rb:160:in `subcommand_class_from'
        12: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:110:in `command_class_from'
        11: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:96:in `load_command'
        10: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:86:in `load_commands'
         9: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:86:in `each'
         8: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:86:in `block in load_commands'
         7: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:86:in `load'
         6: from C:/Users/mcascone.CONSILIO/AppData/Local/chefdk/gem/ruby/2.6.0/gems/knife-vrealize-3.0.0/lib/chef/knife/vra_catalog_list.rb:23:in `<top (required)>'
         5: from C:/opscode/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
         4: from C:/opscode/chefdk/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:123:in `rescue in require'
         3: from C:/opscode/chefdk/embedded/lib/ruby/2.6.0/rubygems.rb:216:in `try_activate'
         2: from C:/opscode/chefdk/embedded/lib/ruby/2.6.0/rubygems.rb:223:in `rescue in try_activate'
         1: from C:/opscode/chefdk/embedded/lib/ruby/2.6.0/rubygems/specification.rb:1418:in `activate'
C:/opscode/chefdk/embedded/lib/ruby/2.6.0/rubygems/specification.rb:2302:in `raise_if_conflicts': Unable to activate knife-vrealize-3.0.0, because knife-cloud-2.0.3 conflicts with knife-cloud (~> 1.2.0) (Gem::ConflictError)
```

**Comment by mcascone** [comment]
The same thing happens with `knife node list` -  it shouldn’t even be looking at any vra stuff?

**Comment by mcascone** [comment]
Pretty sure this is the culprit in `knife-vrealize.gemspec`
```
spec.add_dependency 'knife-cloud',  '~> 1.2.0'
```

**Comment by tas50** [comment]
The dep is loosened in 4.0.3.

**Comment by mcascone** [comment]
@tas50 this does seem to be working now, thanks! 💯
